name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Grant write permissions to the GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Create dist directory
      run: mkdir -p dist

    - name: Copy main.js to dist
      run: cp main.js dist/

    - name: Copy manifest.json to dist
      run: cp manifest.json dist/

    - name: Copy readme.md to dist
      run: cp README.md dist/

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add dist
        git commit -m 'Add build artifacts to dist'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
